# Generated by Django 5.1.4 on 2024-12-30 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_producto_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Venta')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la Venta')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Vendida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='products.producto')),
            ],
        ),
    ]
