# Generated by Django 5.1.5 on 2025-02-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_fecha_venta_fecha_venta_venta_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
