# Generated by Django 5.1.4 on 2024-12-30 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventario_unique_together_and_more'),
        ('products', '0002_remove_cartacolor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidades',
            field=models.PositiveIntegerField(),
        ),
    ]
