# Generated by Django 5.1.4 on 2024-12-30 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventario_fecha_ingreso_alter_inventario_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
