# Generated by Django 5.1.5 on 2025-02-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventario_fecha_ingreso'),
        ('products', '0005_alter_producto_carta_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidades',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades Disponibles'),
        ),
    ]
