# Generated by Django 5.1.4 on 2024-12-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Empleado'), ('common_user', 'Usuario Común')], default='common_user', max_length=15),
        ),
    ]
