# Generated by Django 5.1.3 on 2024-11-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Categoría')),
                ('permite_color', models.BooleanField(default=False, verbose_name='¿Permite Carta de Colores?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Presentación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Presentación')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='CartaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(max_length=50, verbose_name='Código de Color')),
                ('nombre_color', models.CharField(max_length=255, verbose_name='Nombre del Color')),
                ('hexadecimal', models.CharField(blank=True, max_length=7, verbose_name='Código Hexadecimal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_colores', to='products.marca')),
            ],
            options={
                'verbose_name': 'Carta de Color',
                'verbose_name_plural': 'Cartas de Colores',
                'unique_together': {('codigo_color', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(default='Descripción no disponible', verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('carta_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.cartacolor', verbose_name='Carta de Color')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.marca')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.presentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'unique_together': {('nombre', 'marca')},
            },
        ),
    ]
