# Generated by Django 5.1.4 on 2024-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cartacolor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, default='SIN_CODIGO', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
