# Generated by Django 5.1.5 on 2025-01-31 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carta_color',
            field=models.ForeignKey(blank=True, limit_choices_to={'marca': models.F('marca')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.cartacolor', verbose_name='Carta de Color'),
        ),
    ]
