# Generated by Django 5.1.5 on 2025-02-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producto_carta_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carta_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.cartacolor', verbose_name='Carta de Color'),
        ),
    ]
